src/Entity/Trabajador.php
<?php

namespace App\Entity;

use App\Repository\TrabajadorRepository;
use AppBundle\Utils\Exception\FKConstraintViolationException;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TrabajadorRepository::class)
 */
class Trabajador
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombres;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $apellidos;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $carneIdentidad;

    /**
     * @ORM\ManyToOne(targetEntity=Cargo::class, inversedBy="trabajadores")
     */
    private $cargo;

    /**
     * @ORM\OneToOne(targetEntity=Usuario::class, mappedBy="trabajadorAsociado", cascade={"persist", "remove"})
     */
    private $usuario;

    /**
     * @ORM\Column(type="boolean")
     */
    private $alta;

    /**
     * @ORM\Column(type="string", length=255, nullable=true, unique=true)
     */
    private $noExpediente;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $direccionCarne;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $direccionResidencia;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $sexo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $foto;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nivelEducacional;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $fechaAlta;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $fechaBaja;

    /**
     * @ORM\ManyToOne(targetEntity=Municipio::class, inversedBy="trabajadores")
     */
    private $municipio;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $telefono;

    /**
     * @ORM\ManyToMany(targetEntity=Encuentro::class, mappedBy="participantes")
     */
    private $encuentros;

    public function __construct()
    {
        $this->alta = true;
        $this->encuentros = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombres(): ?string
    {
        return $this->nombres;
    }

    public function setNombres(string $nombres): self
    {
        $this->nombres = $nombres;

        return $this;
    }

    public function getApellidos(): ?string
    {
        return $this->apellidos;
    }

    public function setApellidos(?string $apellidos): self
    {
        $this->apellidos = $apellidos;

        return $this;
    }

    public function getCarneIdentidad(): ?string
    {
        return $this->carneIdentidad;
    }

    public function setCarneIdentidad(string $carneIdentidad): self
    {
        $this->carneIdentidad = $carneIdentidad;

        return $this;
    }

    public function getCargo(): ?Cargo
    {
        return $this->cargo;
    }

    public function setCargo(?Cargo $cargo): self
    {
        $this->cargo = $cargo;

        return $this;
    }

    public function getUsuario(): ?Usuario
    {
        return $this->usuario;
    }

    public function setUsuario(?Usuario $usuario): self
    {
        // unset the owning side of the relation if necessary
        if ($usuario === null && $this->usuario !== null) {
            $this->usuario->setTrabajadorAsociado(null);
        }

        // set the owning side of the relation if necessary
        if ($usuario !== null && $usuario->getTrabajadorAsociado() !== $this) {
            $usuario->setTrabajadorAsociado($this);
        }

        $this->usuario = $usuario;

        return $this;
    }
	
	public function getNombreCompleto(): ?string
    {
        return $this->nombres . ' ' . $this->apellidos;
    }

    public function getAlta(): ?bool
    {
        return $this->alta;
    }

    public function setAlta(bool $alta): self
    {
        $this->alta = $alta;

        return $this;
    }

    public function getNoExpediente(): ?string
    {
        return $this->noExpediente;
    }

    public function setNoExpediente(?string $noExpediente): self
    {
        $this->noExpediente = $noExpediente;

        return $this;
    }

    public function getSexo(): ?string
    {
        return $this->sexo;
    }

    public function setSexo(string $sexo): self
    {
        $this->sexo = $sexo;

        return $this;
    }

    public function getFoto(): ?string
    {
        return $this->foto;
    }

    public function setFoto(?string $foto): self
    {
        $this->foto = $foto;

        return $this;
    }

    public function getNivelEducacional(): ?string
    {
        return $this->nivelEducacional;
    }

    public function setNivelEducacional(?string $nivelEducacional): self
    {
        $this->nivelEducacional = $nivelEducacional;

        return $this;
    }

    public function getFechaAlta(): ?\DateTimeInterface
    {
        return $this->fechaAlta;
    }

    public function setFechaAlta(?\DateTimeInterface $fechaAlta): self
    {
        $this->fechaAlta = $fechaAlta;

        return $this;
    }

    public function getFechaBaja(): ?\DateTimeInterface
    {
        return $this->fechaBaja;
    }

    public function setFechaBaja(?\DateTimeInterface $fechaBaja): self
    {
        $this->fechaBaja = $fechaBaja;

        return $this;
    }

    public function getMunicipio(): ?Municipio
    {
        return $this->municipio;
    }

    public function setMunicipio(?Municipio $municipio): self
    {
        $this->municipio = $municipio;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(?string $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getDireccionCarne(): ?string
    {
        return $this->direccionCarne;
    }

    public function setDireccionCarne(?string $direccionCarne): self
    {
        $this->direccionCarne = $direccionCarne;

        return $this;
    }

    public function getDireccionResidencia(): ?string
    {
        return $this->direccionResidencia;
    }

    public function setDireccionResidencia(?string $direccionResidencia): self
    {
        $this->direccionResidencia = $direccionResidencia;

        return $this;
    }

    /**
     * @return Collection|Encuentro[]
     */
    public function getEncuentros(): Collection
    {
        return $this->encuentros;
    }

    public function addEncuentro(Encuentro $encuentro): self
    {
        if (!$this->encuentros->contains($encuentro)) {
            $this->encuentros[] = $encuentro;
            $encuentro->addParticipante($this);
        }

        return $this;
    }

    public function removeEncuentro(Encuentro $encuentro): self
    {
        if ($this->encuentros->removeElement($encuentro)) {
            $encuentro->removeParticipante($this);
        }

        return $this;
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemove() {
        if ($this->encuentros->count() > 0) {
            throw new FKConstraintViolationException();
        }
   }

}

src/Controller/DefaultController.php
<?php


namespace App\Controller;


use App\Entity\Encuentro;
use App\Entity\EncuentroAcuerdo;
use App\Entity\Rol;
use App\Entity\SolicitudMateriales;
use App\Repository\SistemaModuloRepository;
use App\Repository\SistemaRutaRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\UX\Chartjs\Builder\ChartBuilderInterface;
use Symfony\UX\Chartjs\Model\Chart;

class DefaultController extends BaseController
{

    private $sistemaRutaRepository;

    private $sistemaModuloRepository;

    public function __construct(SistemaRutaRepository $sistemaRutaRepository, SistemaModuloRepository $sistemaModuloRepository)
    {
        $this->sistemaRutaRepository = $sistemaRutaRepository;
        $this->sistemaModuloRepository = $sistemaModuloRepository;
    }

    /**
     * @Route("/",name="app_index")
     */
    public function index(ChartBuilderInterface $chartBuilder){
        $acuerdos = $this->getDoctrine()->getRepository(EncuentroAcuerdo::class)->findAll();
        $encuentros = $this->getDoctrine()->getRepository(Encuentro::class)->findAll();
        $solicitudesMateriales = $this->getDoctrine()->getRepository(SolicitudMateriales::class)->findAll();
        $acuerdosPorTipo = array();
        $encuentrosPorTipo = array();


        foreach ($acuerdos as $item){
            if(isset($acuerdosPorTipo[$item->getUltimoEstado()]))  {
                $acuerdosPorTipo[$item->getUltimoEstado()] ++;
            } else {
                $acuerdosPorTipo[$item->getUltimoEstado()] = 1;
            }
        }

        foreach ($encuentros as $item){
            if(isset($encuentrosPorTipo[$item->getEstado()]))  {
                $encuentrosPorTipo[$item->getEstado()] ++;
            } else {
                $encuentrosPorTipo[$item->getEstado()] = 1;
            }
        }

        $chartjs = $chartBuilder->createChart(Chart::TYPE_LINE);
        $chartjs->setData([
            'labels' => ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
            'datasets' => [
                [
                    'label' => 'My First dataset',
                    'backgroundColor' => '[rgb(255, 99, 132), rgb(0, 99, 100)]',
                    'borderColor' => 'rgb(255, 99, 132)',
                    'data' => [0, 10, 5, 2, 20, 30, 45],
                ],
            ],
        ]);

        $chart = $chartBuilder->createChart(Chart::TYPE_PIE);
        $chart->setData([
           
            'datasets' => [
                [
                    'label' => 'My First dataset',
                    'backgroundColor' => [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    'data' => [0, 10, 5, 2, 20, 30, 45],
                ],
            ],
        ]);



        return $this->render("default/main.html.twig", array(
            'encuentros' => $encuentros,
            'acuerdos' => $acuerdos,
            'acuerdos_tipos' => $acuerdosPorTipo,
            'encuentros_tipos' => $encuentrosPorTipo,
            'solicitudes_materiales' => $solicitudesMateriales,
            'chartjs' => $chartjs,
            'chart' => $chart
        ));
    }

    /**
     * @Route("/assets/iconos",name="app_iconos")
     */
    public function iconos(){
        $iconsFA = array("fa-500px","fa-adjust","fa-adn","fa-align-center","fa-align-justify","fa-align-left","fa-align-right",
            "fa-amazon","fa-ambulance","fa-american-sign-language-interpreting","fa-anchor","fa-android","fa-angellist","fa-angle-double-down","fa-angle-double-left","fa-angle-double-right","fa-angle-double-up",
            "fa-angle-down","fa-angle-left","fa-angle-right","fa-angle-up","fa-apple","fa-archive","fa-area-chart","fa-arrow-circle-down","fa-arrow-circle-left","fa-arrow-circle-o-down","fa-arrow-circle-o-left",
            "fa-arrow-circle-o-right","fa-arrow-circle-o-up","fa-arrow-circle-right","fa-arrow-circle-up","fa-arrow-down","fa-arrow-left","fa-arrow-right","fa-arrow-up","fa-arrows","fa-arrows-alt","fa-arrows-h",
            "fa-arrows-v","fa-assistive-listening-systems","fa-asterisk","fa-at","fa-audio-description","fa-backward","fa-balance-scale","fa-ban","fa-bar-chart","fa-barcode","fa-bars",
            "fa-battery-empty","fa-battery-full","fa-battery-half","fa-battery-quarter","fa-battery-three-quarters","fa-bed","fa-beer","fa-behance","fa-behance-square","fa-bell","fa-bell-o","fa-bell-slash",
            "fa-bell-slash-o","fa-bicycle","fa-binoculars","fa-birthday-cake","fa-bitbucket","fa-bitbucket-square","fa-black-tie","fa-blind","fa-bluetooth","fa-bluetooth-b","fa-bold","fa-bolt","fa-bomb","fa-book",
            "fa-bookmark","fa-bookmark-o","fa-braille","fa-briefcase","fa-btc","fa-bug","fa-building","fa-building-o","fa-bullhorn","fa-bullseye","fa-bus","fa-buysellads","fa-calculator","fa-calendar",
            "fa-calendar-check-o","fa-calendar-minus-o","fa-calendar-o","fa-calendar-plus-o","fa-calendar-times-o","fa-camera","fa-camera-retro","fa-car","fa-caret-down","fa-caret-left","fa-caret-right",
            "fa-caret-square-o-down","fa-caret-square-o-left","fa-caret-square-o-right","fa-caret-square-o-up","fa-caret-up","fa-cart-arrow-down","fa-cart-plus","fa-cc","fa-cc-amex","fa-cc-diners-club",
            "fa-cc-discover","fa-cc-jcb","fa-cc-mastercard","fa-cc-paypal","fa-cc-stripe","fa-cc-visa","fa-certificate","fa-chain-broken","fa-check","fa-check-circle","fa-check-circle-o","fa-check-square",
            "fa-check-square-o","fa-chevron-circle-down","fa-chevron-circle-left","fa-chevron-circle-right","fa-chevron-circle-up","fa-chevron-down","fa-chevron-left","fa-chevron-right","fa-chevron-up","fa-child",
            "fa-chrome","fa-circle","fa-circle-o","fa-circle-o-notch","fa-circle-thin","fa-clipboard","fa-clock-o","fa-clone","fa-cloud","fa-cloud-download","fa-cloud-upload","fa-code","fa-code-fork","fa-codepen",
            "fa-codiepie","fa-coffee","fa-cog","fa-cogs","fa-columns","fa-comment","fa-comment-o","fa-commenting","fa-commenting-o","fa-comments","fa-comments-o","fa-compass","fa-compress","fa-connectdevelop",
            "fa-contao","fa-copyright","fa-creative-commons","fa-credit-card","fa-credit-card-alt","fa-crop","fa-crosshairs","fa-css3","fa-cube","fa-cubes","fa-cutlery","fa-dashcube","fa-database","fa-deaf",
            "fa-delicious","fa-desktop","fa-deviantart","fa-diamond","fa-digg","fa-dot-circle-o","fa-download","fa-dribbble","fa-dropbox","fa-drupal","fa-edge","fa-eject","fa-ellipsis-h","fa-ellipsis-v",
            "fa-empire","fa-envelope","fa-envelope-o","fa-envelope-square","fa-envira","fa-eraser","fa-eur","fa-exchange","fa-exclamation","fa-exclamation-circle",
            "fa-exclamation-triangle","fa-expand","fa-expeditedssl","fa-external-link","fa-external-link-square","fa-eye","fa-eye-slash","fa-eyedropper","fa-facebook","fa-facebook-official","fa-facebook-square",
            "fa-fast-backward","fa-fast-forward","fa-fax","fa-female","fa-fighter-jet","fa-file","fa-file-archive-o","fa-file-audio-o","fa-file-code-o","fa-file-excel-o","fa-file-image-o","fa-file-o","fa-file-pdf-o",
            "fa-file-powerpoint-o","fa-file-text","fa-file-text-o","fa-file-video-o","fa-file-word-o","fa-files-o","fa-film","fa-filter","fa-fire","fa-fire-extinguisher","fa-firefox","fa-first-order","fa-flag",
            "fa-flag-checkered","fa-flag-o","fa-flask","fa-flickr","fa-floppy-o","fa-folder","fa-folder-o","fa-folder-open","fa-folder-open-o","fa-font","fa-font-awesome","fa-fonticons","fa-fort-awesome","fa-forumbee",
            "fa-forward","fa-foursquare","fa-frown-o","fa-futbol-o","fa-gamepad","fa-gavel","fa-gbp","fa-genderless","fa-get-pocket","fa-gg","fa-gg-circle","fa-gift","fa-git","fa-git-square",
            "fa-github","fa-github-alt","fa-github-square","fa-gitlab","fa-glass","fa-glide","fa-glide-g","fa-globe","fa-google","fa-google-plus","fa-google-plus-official","fa-google-plus-square","fa-google-wallet",
            "fa-graduation-cap","fa-gratipay","fa-h-square","fa-hacker-news","fa-hand-lizard-o","fa-hand-o-down","fa-hand-o-left","fa-hand-o-right","fa-hand-o-up","fa-hand-paper-o","fa-hand-peace-o",
            "fa-hand-pointer-o","fa-hand-rock-o","fa-hand-scissors-o","fa-hand-spock-o","fa-hashtag","fa-hdd-o","fa-header","fa-headphones","fa-heart","fa-heart-o","fa-heartbeat","fa-history",
            "fa-home","fa-hospital-o","fa-hourglass","fa-hourglass-end","fa-hourglass-half","fa-hourglass-o","fa-hourglass-start","fa-houzz","fa-html5","fa-i-cursor",
            "fa-ils","fa-inbox","fa-indent","fa-industry","fa-info","fa-info-circle","fa-inr","fa-instagram","fa-internet-explorer","fa-ioxhost","fa-italic","fa-joomla","fa-jpy","fa-jsfiddle","fa-key",
            "fa-keyboard-o","fa-krw","fa-language","fa-laptop","fa-lastfm","fa-lastfm-square","fa-leaf","fa-leanpub","fa-lemon-o","fa-level-down","fa-level-up","fa-life-ring","fa-lightbulb-o","fa-line-chart",
            "fa-link","fa-linkedin","fa-linkedin-square","fa-linux","fa-list","fa-list-alt","fa-list-ol","fa-list-ul","fa-location-arrow","fa-lock","fa-long-arrow-down","fa-long-arrow-left",
            "fa-long-arrow-right","fa-long-arrow-up","fa-low-vision","fa-magic","fa-magnet","fa-male","fa-map","fa-map-marker","fa-map-o","fa-map-pin","fa-map-signs","fa-mars","fa-mars-double","fa-mars-stroke",
            "fa-mars-stroke-h","fa-mars-stroke-v","fa-maxcdn","fa-meanpath","fa-medium","fa-medkit","fa-meh-o","fa-mercury","fa-microphone","fa-microphone-slash","fa-minus",
            "fa-minus-circle","fa-minus-square","fa-minus-square-o","fa-mixcloud","fa-mobile","fa-modx","fa-money","fa-moon-o","fa-motorcycle","fa-mouse-pointer","fa-music","fa-neuter","fa-newspaper-o",

templates/default/bars-menu.html.twig
<li><a href="{{ path('app_index') }}"><i class="fa fa-home"></i> Inicio</a></li>
{% for elem in main_menu %}
    {% if elem.mostrar is defined and elem.mostrar == true %}
    <li><a><i class="fa fa-{{ elem.icono }}"></i> {{ elem.nombre }} <span class="fa fa-chevron-down"></span></a>
        {% if elem.rutas is defined and elem.rutas|length > 0 %}
            <ul class="nav child_menu">
                {% for submenu in elem.rutas %}
                    {% if submenu.mostrar is defined and submenu.mostrar == true %}
                    <li>
                        <a href="{{ submenu.enlace is defined and submenu.enlace != '' ? submenu.enlace : '#' }}">{{ submenu.nombre }}
                            {% if submenu.icono is defined and submenu.icono != '' %}
                                <span class="fa fa-{{ submenu.icono }}"></span>
                            {% endif %}
                        </a>
                    </li>
                    {% endif %}
                {% endfor %}
            </ul>
            </li>
        {% endif %}
    {% endif %}
{% endfor %}

templates/default/bars.html.twig
{% extends "defaultbase.html.twig" %}
{% block bars %}
    <div class="col-md-3 left_col menu_fixed">
        <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
                <a href="{{ path('app_index') }}" class="site_title"><img src="{{ asset('images/logo_cuadrado.png') }}"> <span>SAGEP</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
                <div class="profile_pic">
                    {% set trabajador = app.user.trabajadorAsociado %}
                    <img src="
                        {{ trabajador is null ? asset('images/avatar_default.png') : trabajador.foto is not null ? asset('assets/fotosTrabajadores/' ~ trabajador.foto) : trabajador.sexo == 'Femenino' ? asset('images/femenino.jpg') : asset('images/masculino.jpg') }}
                    " alt="..." class="img-circle profile_img">

                </div>
                <div class="profile_info">
                    <span>Bienvenido(a),</span>
                    <h2>{{ app.user.nombreCompleto }}</h2>
                </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                <div class="menu_section">
                    <ul class="nav side-menu">
                        {{ render(controller('App\\Controller\\DefaultController::renderBarsMenu')) }}
                    </ul>
                </div>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
                <a data-toggle="tooltip" data-placement="top" title="" data-original-title="Settings">
                    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                </a>
                <a data-toggle="tooltip" data-placement="top" title="" data-original-title="FullScreen">
                    <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                </a>
                <a data-toggle="tooltip" data-placement="top" title="" data-original-title="Lock">
                    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                </a>
                <a data-toggle="tooltip" data-placement="top" title="" href="login.html" data-original-title="Logout">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                </a>
            </div>
        </div>
    </div>

    <!-- top navigation -->
    <div class="top_nav">
        <div class="nav_menu">
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>
            <nav class="nav navbar-nav">
                <ul class=" navbar-right">
                    <li class="nav-item dropdown open" style="padding-left: 15px;">
                        <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                            <img src="
                                {{ trabajador is null ? asset('images/avatar_default.png') : trabajador.foto is not null ? asset('assets/fotosTrabajadores/' ~ trabajador.foto) : trabajador.sexo == 'Femenino' ? asset('images/femenino.jpg') : asset('images/masculino.jpg') }}
                            " alt="">{{ app.user.nombreCompleto }}
                        </a>
                        <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item"  href="{{ path('app_cambiar_contrasenna', {'user' : app.user.username }) }}"><i class="fa fa-key pull-right"></i>Cambiar mi contraseña</a>
                            <a class="dropdown-item"  href="{{ path('app_logout') }}"><i class="fa fa-sign-out pull-right"></i>Cerrar sesión</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown open" role="presentation" id="top-bar-busqueda-avanzada">
                        <a href="{{ path('app_busqueda_avanzada') }}">
                            <i class="fa fa-search"></i>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
    <!-- /top navigation -->

    <!-- page content -->
    <div class="right_col" role="main">
        {% for message in app.flashes("error") %}
            <div class="alert alert-danger alert-dismissible " role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
                </button>
                <strong>Error</strong> {{ message }}
            </div>
        {% endfor %}
        {% for message in app.flashes("success") %}
            <div class="alert alert-success alert-dismissible " role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
                </button>
                <strong>Éxito</strong> {{ message }}
            </div>
        {% endfor %}
        {% block contenpage %}{% endblock %}
    </div>
    <!-- /page content -->
{% endblock %}

templates/default/content.html.twig
{% extends "admin/bars.html.twig" %}

{% block contenpage %}
    <h1>main</h1>
{% endblock %}

templates/default/render-controller-info.html.twig
{{ result }}

templates/default/tpl-comentario-unico.html.twig
<li class="list-group-item {% if comentario.comentarioPadre is not null %} pb-0 pr-0 border-top-0{% endif %}">
    <div class="row p-1">
        <div class="col-xs-2 col-md-1">
            {% set trabajador = comentario.usuario.trabajadorAsociado %}
            <img src="
                    {{ trabajador is null ? asset('images/avatar_default.png') : trabajador.foto is not null ? asset('assets/fotosTrabajadores/' ~ trabajador.foto) : trabajador.sexo == 'Femenino' ? asset('images/femenino.jpg') : asset('images/masculino.jpg') }}
                    " width="60px" class="img-circle img-responsive" alt="" /></div>
        <div class="col-xs-10 col-md-11 comentario-area">
            <div class="comentario-info">
                <div>
                    <div class="mic-info">
                        Por: <a href="{{ path('usuario_editar', {'id' : comentario.usuario.id }) }}">{{ comentario.usuario.nombreCompleto }}</a> el {{ comentario.fechaCreado | date('d-m-Y h:i:s a') }}
                        {% if comentario.fechaCreado != comentario.fechaModificado or comentario.usuario != comentario.usuarioUltimaModificacion %}
                        , Última modificación: <a href="{{ path('usuario_editar', {'id' : comentario.usuario.id }) }}">{{ comentario.usuarioUltimaModificacion.nombreCompleto }}</a> el {{ comentario.fechaCreado | date('d-m-Y h:i:s a') }}
                        {% endif %}
                    </div>
                </div>
                <div class="comment-text">{{ comentario.comentario }}</div>
                <div class="action">
                    {% if comentario.usuario.id == app.user.id %}
                        <button type="button" href="{{ path('comentario_editar', {'id' : comentario.id}) }}" class="btn btn-success btn-xs editar-comentario">
                            <i class="fa fa-pencil"></i>
                        </button>
                    {% endif %}
                        <button type="button" href="{{ path('comentario_responder', {'id' : comentario.id}) }}"  class="btn btn-primary btn-xs responder-comentario">
                            <i class="fa fa-reply"></i>
                        </button>
                    {% if is_granted("ROLE_DIRECTOR_AREA") %}
                        <button type="button" href="{{ path('comentario_eliminar', {'id' : comentario.id}) }}"  class="btn btn-danger btn-xs del-comentario-list-item">
                            <i class="fa fa-trash"></i>
                        </button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% for comentario in comentario.respuestas | sort((a,b) => a.fechaModificado < b.fechaModificado) %}
        <div class="row pl-2 pb-0">
            <ul class="pl-2 pb-0 w-100">
                {{ include('default/tpl-comentario-unico.html.twig') }}
            </ul>
        </div>
    {% endfor %}
</li>

templates/default/tpl-lock.html.twig
<div class="col-md-12">
    <div class="x_panel">
        Los elementos marcados con el icono <i class="text-danger fa fa-lock"></i> no se pueden eliminar, ya que cuentan con elementos dependientes.
        Cuando realice eliminaciones en grupo, tenga en cuenta que ninguno de los elementos bloqueados esté marcado.
    </div>
</div>